sudo: false
language: java
jdk:
  - oraclejdk8
  
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.3-unix.tar.gz
  - tar -xzf neo4j-community-2.2.3-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.3/conf/neo4j-server.properties
  - neo4j-community-2.2.3/bin/neo4j start

services:
  - couchdb
  - mongodb
  
after_success:
  - mvn test javadoc:javadoc
 
notifications:
  email: false