#cluster:
#  zookeeper:
#    hostPort: localhost:2181
#    sessionTimeout: 100000
agent_server:
  jetty:
    host: localhost
    port: 10800
    context_path: /
agent_stream:
  grpc:
    host: localhost
    port: 11800
  jetty:
    host: localhost
    port: 12800
    context_path: /
  config:
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
collector_inside:
  grpc:
    host: localhost
    port: 11800
#storage:
#  elasticsearch:
#    cluster_name: CollectorDBCluster
#    cluster_transport_sniffer: true
#    cluster_nodes: localhost:9300
#    index_shards_number: 2
#    index_replicas_number: 0